CREATE TABLE `intake_submissions` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`created_at` text DEFAULT CURRENT_TIMESTAMP NOT NULL,
	`first_name` text NOT NULL,
	`last_name` text NOT NULL,
	`date_of_birth` text NOT NULL,
	`gender` text,
	`phone` text NOT NULL,
	`email` text NOT NULL,
	`address1` text NOT NULL,
	`address2` text,
	`city` text NOT NULL,
	`state` text NOT NULL,
	`zip` text NOT NULL,
	`emergency_name` text NOT NULL,
	`emergency_relationship` text NOT NULL,
	`emergency_phone` text NOT NULL,
	`uninsured` integer DEFAULT false NOT NULL,
	`insurance_provider` text,
	`member_id` text,
	`group_number` text,
	`insured_name` text,
	`primary_substance` text NOT NULL,
	`other_substances` text,
	`frequency` text NOT NULL,
	`duration` text NOT NULL,
	`last_use_date` text,
	`route_of_use` text,
	`amount_per_use` text,
	`current_medications` text,
	`allergies` text,
	`chronic_conditions` text,
	`mental_health_diagnoses` text,
	`suicide_risk` text,
	`seizures_history` text,
	`pregnancy_status` text,
	`prior_treatment` text,
	`prior_facilities` text,
	`legal_issues` text,
	`court_mandated` text,
	`probation_officer` text,
	`detox_needed` text,
	`hipaa_consent` integer NOT NULL,
	`contact_consent` integer NOT NULL,
	`agree_to_terms` integer NOT NULL,
	`submitted_at` text
);
